# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.content_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_widget.sizePolicy().hasHeightForWidth())
        self.content_widget.setSizePolicy(sizePolicy)
        self.content_widget.setObjectName("content_widget")
        self.gridLayout.addWidget(self.content_widget, 0, 2, 1, 1)
        self.menu_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_widget.sizePolicy().hasHeightForWidth())
        self.menu_widget.setSizePolicy(sizePolicy)
        self.menu_widget.setMinimumSize(QtCore.QSize(160, 0))
        self.menu_widget.setObjectName("menu_widget")
        self.main_menu_label = QtWidgets.QLabel(self.menu_widget)
        self.main_menu_label.setGeometry(QtCore.QRect(0, 0, 153, 19))
        self.main_menu_label.setObjectName("main_menu_label")
        self.stock_button = QtWidgets.QPushButton(self.menu_widget)
        self.stock_button.setGeometry(QtCore.QRect(0, 20, 153, 27))
        self.stock_button.setObjectName("stock_button")
        self.bills_button = QtWidgets.QPushButton(self.menu_widget)
        self.bills_button.setGeometry(QtCore.QRect(0, 50, 153, 27))
        self.bills_button.setObjectName("bills_button")
        self.orders_button = QtWidgets.QPushButton(self.menu_widget)
        self.orders_button.setGeometry(QtCore.QRect(0, 80, 153, 27))
        self.orders_button.setObjectName("orders_button")
        self.gridLayout.addWidget(self.menu_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_menu_label.setText(_translate("MainWindow", "Main menu"))
        self.stock_button.setText(_translate("MainWindow", "Sklad"))
        self.bills_button.setText(_translate("MainWindow", "Prodej"))
        self.orders_button.setText(_translate("MainWindow", "Objednavky"))
