# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 138)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_label = QtWidgets.QLabel(Form)
        self.login_label.setObjectName("login_label")
        self.verticalLayout.addWidget(self.login_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.username_label = QtWidgets.QLabel(Form)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.username_edit = QtWidgets.QLineEdit(Form)
        self.username_edit.setObjectName("username_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_edit)
        self.password_edit = QtWidgets.QLineEdit(Form)
        self.password_edit.setObjectName("password_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_label.setText(_translate("Form", "Login"))
        self.username_label.setText(_translate("Form", "Username:"))
        self.password_label.setText(_translate("Form", "Password:"))
        self.login_button.setText(_translate("Form", "Login"))
